name: project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
# General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dio: ^4.0.0
  # for function prog. error handling
  dartz: ^0.9.2
  # for local storage
  localstorage: ^4.0.0+1
  # for state management||service locator
  provider: ^5.0.0
  # for dependency injection
  get_it: ^7.1.1
  # unique user id
  uuid: ^3.0.4
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  intl: ^0.17.0
  fake_cloud_firestore: ^1.1.2

  # search bar
  search_widget: ^1.0.2

dev_dependencies:
  # mock http dio
  http_mock_adapter: ^0.3.1
  mockito:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 

